
networks:
  default:
    name: care

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./docker/.prebuilt.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis/redis-stack-server:6.2.6-v10
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    volumes:
      - "${TEMPDIR:-./care/media/localstack}:/var/lib/localstack"
      - "./docker/awslocal:/etc/localstack/init/ready.d/"
    ports:
      - "4566:4566"

volumes:
  postgres-data:
  redis-data:
