version: '3.4'

services:

  backend:
    image: "ghcr.io/coronasafe/care:latest"
    env_file:
      - ./docker/.prebuilt.env
    entrypoint: [ "bash", "start-ecs.sh" ]
    depends_on:
      - db
      - redis
    ports:
      - "9000:9000"

  celery-worker:
    image: "ghcr.io/coronasafe/care:latest"
    env_file:
      - ./docker/.prebuilt.env
    entrypoint: [ "bash", "celery_worker-ecs.sh" ]
    depends_on:
      - db
      - backend
      - redis

  celery-beat:
    image: "ghcr.io/coronasafe/care:latest"
    env_file:
      - ./docker/.prebuilt.env
    entrypoint: [ "bash", "celery_beat-ecs.sh" ]
    depends_on:
      - db
      - backend
      - redis
