name: Deploy Care
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  IMAGE_NAME: care
  AWS_DEFAULT_REGION: ap-south-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  build-dockerhub-staging:
    needs: test
    name: Build & Push to Dockerhub
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current date as ENV variable
        run: echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Github Short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Push image
        run: |
          IMAGE_ID=${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION-$GITHUB_RUN_NUMBER-$NOW-$SHORT_SHA
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID --all-tags
  build-github-staging:
    needs: test
    if: github.ref == 'refs/heads/master'
    name: Build and push to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set current date as ENV variable
        run: echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Github Short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION-$GITHUB_RUN_NUMBER-$NOW-$SHORT_SHA
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID --all-tags
  deploy-staging-egov:
    needs: build-github-staging
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment:
      name: Staging-egov
      url: https://careapi.coronasafe.in
    steps:
      - name: Checkout Kube Config
        uses: actions/checkout@v2
        with:
          repository: coronasafe/infra
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: kube
          ref: main
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy Care Staging
        run: |
          mkdir -p $HOME/.kube/
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ap-south-1
          cd kube/deployments/
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-backend.yaml
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-celery-beat.yaml
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-celery-worker.yaml
          kubectl apply -f care-backend.yaml
          kubectl apply -f care-celery-beat.yaml
          kubectl apply -f care-celery-worker.yaml

  deploy-staging-gdc:
    needs: build-github-staging
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment:
      name: Staging-gdc
      url: https://gdcapi.coronasafe.network
    steps:
      - name: Checkout Kube Config
        uses: actions/checkout@v2
        with:
          repository: coronasafe/gdc_infra
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: kube
          ref: main
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy Care Staging
        run: |
          mkdir -p $HOME/.kube/
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ap-south-1
          cd kube/deployments/
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-backend.yaml
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-celery-beat.yaml
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-celery-worker.yaml
          kubectl apply -f care-backend.yaml
          kubectl apply -f care-celery-beat.yaml
          kubectl apply -f care-celery-worker.yaml
